app/routes/auth.py
from app.models.user import User
from app.utils.user import create_user
from app.forms.auth import LoginForm, RegistrationForm
from app.routes.google_auth import google_logout
from flask import Blueprint, url_for, flash, redirect, request, render_template
from flask_login import login_user, logout_user

auth = Blueprint('auth', __name__, template_folder='templates')


@auth.route('/login', methods=['POST'])
def login():
    form = LoginForm(**request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user, remember=form.remember.data)
        next_url = request.args.get('next', 'base.index')
        return redirect(url_for(next_url))
    return render_template('home/index.html',
                           login_form=form,
                           registration_form=RegistrationForm(),
                           js_vars={
                               'invalidFormButton': 'login-btn'
                           })


@auth.route('/register', methods=['POST'])
def register():
    form = RegistrationForm(**request.form)
    if form.validate_on_submit():
        user = create_user(email=form.email.data, password=form.password.data, army_name=form.army_name.data)
        login_user(user, remember=False)
        return redirect(url_for('home.index'))
    return render_template('home/index.html',
                           login_form=LoginForm(),
                           registration_form=form,
                           js_vars={
                               'invalidFormButton': 'registration-btn'
                           })


@auth.route('/logout')
def logout():
    # logout possible google user
    google_logout()
    logout_user()
    flash('You are now logged out')
    return redirect(url_for('home.index'))

app/routes/google_auth.py
import functools
import os
import flask
import google.oauth2.credentials
import googleapiclient.discovery
from app import db
from app.models.user import User
from app.models.army import Army, Upgrade
from dotenv import load_dotenv
from authlib.client import OAuth2Session
from flask_login import login_user, current_user
from flask import url_for

ACCESS_TOKEN_URI = 'https://www.googleapis.com/oauth2/v4/token'
AUTHORIZATION_URL = 'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent'

AUTHORIZATION_SCOPE = 'openid email profile'

load_dotenv()

AUTH_REDIRECT_URI = os.getenv("FN_AUTH_REDIRECT_URI")
BASE_URI = os.getenv("FN_BASE_URI")
CLIENT_ID = os.getenv("FN_CLIENT_ID")
CLIENT_SECRET = os.getenv("FN_CLIENT_SECRET")

AUTH_TOKEN_KEY = 'auth_token'
AUTH_STATE_KEY = 'auth_state'

google_auth = flask.Blueprint('google_auth', __name__, template_folder='templates')


def is_logged_in():
    return True if AUTH_TOKEN_KEY in flask.session else False


def build_credentials():
    if not is_logged_in():
        raise Exception('User must be logged in')

    oauth2_tokens = flask.session[AUTH_TOKEN_KEY]

    return google.oauth2.credentials.Credentials(
        oauth2_tokens['access_token'],
        refresh_token=oauth2_tokens['refresh_token'],
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        token_uri=ACCESS_TOKEN_URI)


def get_user_info():
    credentials = build_credentials()

    oauth2_client = googleapiclient.discovery.build(
        'oauth2', 'v2',
        credentials=credentials)

    return oauth2_client.userinfo().get().execute()


def no_cache(view):
    @functools.wraps(view)
    def no_cache_impl(*args, **kwargs):
        response = flask.make_response(view(*args, **kwargs))
        response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
        response.headers['Pragma'] = 'no-cache'
        response.headers['Expires'] = '-1'
        return response

    return functools.update_wrapper(no_cache_impl, view)


@google_auth.route('/login')
@no_cache
def login():
    if current_user.is_authenticated:
        return flask.redirect(url_for('base.index'))
    session = OAuth2Session(CLIENT_ID, CLIENT_SECRET,
                            scope=AUTHORIZATION_SCOPE,
                            redirect_uri=AUTH_REDIRECT_URI)

    uri, state = session.authorization_url(AUTHORIZATION_URL)

    flask.session[AUTH_STATE_KEY] = state
    flask.session.permanent = True
    return flask.redirect(uri, code=302)


@google_auth.route('/auth')
@no_cache
def google_auth_redirect():
    if current_user.is_authenticated:
        return flask.redirect(url_for('base.index'))
    req_state = flask.request.args.get('state', default=None, type=None)

    if req_state != flask.session[AUTH_STATE_KEY]:
        return flask.make_response('Invalid state parameter', 401)

    session = OAuth2Session(CLIENT_ID, CLIENT_SECRET,
                            scope=AUTHORIZATION_SCOPE,
                            state=flask.session[AUTH_STATE_KEY],
                            redirect_uri=AUTH_REDIRECT_URI)

    oauth2_tokens = session.fetch_access_token(
        ACCESS_TOKEN_URI,
        authorization_response=flask.request.url)

    flask.session[AUTH_TOKEN_KEY] = oauth2_tokens

    google_user = get_user_info()
    email = google_user.get('email')
    avatar = google_user.get('picture')

    existing_user = User.query.filter_by(email=email).first()

    if not existing_user:
        user = User(email=email, avatar=avatar, is_google_user=True)
        db.session.add(user)
        db.session.commit()
        army = Army(user_id=user.id)
        db.session.add(army)
        db.session.commit()
        upgrade = Upgrade(army_id=user.id)
        db.session.add(upgrade)
        db.session.commit()
        login_user(user)
    else:
        login_user(existing_user)

    return flask.redirect(BASE_URI, code=302)


@no_cache
def google_logout():
    flask.session.pop(AUTH_TOKEN_KEY, None)
    flask.session.pop(AUTH_STATE_KEY, None)

    return flask.redirect(BASE_URI, code=302)

app/routes/home.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user
from app import db
from app.utils.user import create_user
from app.models.user import User
from app.models.army import Army, Upgrade
from app.forms.auth import LoginForm, RegistrationForm

home = Blueprint('home', __name__, template_folder='templates')


@home.route('/', methods=['GET', 'POST'])
def index():
    login_form = LoginForm()
    registration_form = RegistrationForm()

    return render_template('home/index.html',
                           login_form=login_form,
                           registration_form=registration_form)

app/templates/home/index.html
{% extends "layout.html" %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{%  endblock styles %}
{% block title %} <title> Home </title> {% endblock title %}
{% block content %}
    <div class="auth-messages text-center mt-4 bg-info">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% if not current_user.is_authenticated %}
        <div id="login-form">
            <div class="popup-background">
                <div class="popup">
                    <form method="POST" class="text-center" action="{{ url_for('auth.login') }}">
                        {{ login_form.hidden_tag() }}
                        <p class="h4 mb-4">Sign in</p>
                        {% if login_form.email.errors %}
                            {{ login_form.email(class="form-control is-invalid") }}
                            {% for error in login_form.email.errors %}
                                <div class= "invalid-feedback mb-4"> {{ error }} </div>
                            {% endfor %}
                        {% else %}
                            {{ login_form.email(class="form-control mb-4") }}
                        {% endif %}

                        {% if login_form.password.errors %}
                            {{ login_form.password(class="form-control invalid-feedback") }}
                            {% for error in login_form.password.errors %}
                                <div class= "invalid-feedback mb-4"> {{ error }} </div>
                            {% endfor %}

                        {% else %}
                            {{ login_form.password(class="form-control mb-4") }}
                        {% endif %}

                        <div class="d-flex justify-content-around">
                            <div>
                                <div class="custom-control custom-checkbox">
                                    {{ login_form.remember(class="custom-control-input") }}
                                    {{ login_form.remember.label(class="custom-control-label") }}
                                </div>
                            </div>
    {#                        <div>#}
    {#                            <a href="">Forgot password?</a>#}
    {#                        </div>#}
                        </div>

                        <button class="btn btn-dark btn-block my-4" type="submit">Login</button>

                        <p>or login with:</p>
                        <a href="{{ url_for('google_auth.login') }}" class="light-blue-text">
                            <i class="fab fa-google"></i>
                        </a>
                    </form>
                </div>
            </div>
        </div>
        <div id="registration-form">
            <div class="popup-background">
                <div class="popup">
                    <form method="POST" class="text-center" action="{{ url_for('auth.register') }}">
                        {{ registration_form.hidden_tag() }}
                        <p class="h4 mb-4">Register</p>
                        <div class="form-group">
                            {% if registration_form.email.errors %}
                                {{ registration_form.email(class="form-control is-invalid") }}
                                {% for error in registration_form.email.errors %}
                                    <div class= "invalid-feedback"> {{ error }} </div>
                                {% endfor %}
                            {% else %}
                                {{ registration_form.email(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if registration_form.password.errors %}
                                {{ registration_form.password(class="form-control is-invalid") }}
                                {% for error in registration_form.password.errors %}
                                    <div class= "invalid-feedback"> {{ error }} </div>
                                {% endfor %}
                            {% else %}
                                
                                {{ registration_form.password(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if registration_form.confirm_password.errors %}
                                {{ registration_form.confirm_password(class="form-control is-invalid") }}
                                {% for error in registration_form.confirm_password.errors %}
                                    <div class= "invalid-feedback"> {{ error }} </div>
                                {% endfor %}
                            {% else %}
                                {{ registration_form.confirm_password(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {% if registration_form.army_name.errors %}
                                {{ registration_form.army_name(class="form-control is-invalid") }}
                                {% for error in registration_form.army_name.errors %}
                                    <div class= "invalid-feedback"> {{ error }} </div>
                                {% endfor %}
                            {% else %}
                                {{ registration_form.army_name(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-dark btn-block my-4" type="submit">Register</button>
                        </div>
                        <p>or register with:</p>
                        <div class="form-group text-center">
                            <a href="{{ url_for('google_auth.login') }}">
                                <i class="fab fa-google"></i>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock scripts %}