app/forms/profile.py
from app.models.army import Army
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length, ValidationError


class SetArmyNameForm(FlaskForm):
    army_name = StringField('Army name',
                            validators=[DataRequired(), Length(min=3, max=16)],
                            render_kw={'placeholder': 'Army Name'})

    @staticmethod
    def validate_army_name(_, army_name):
        army = Army.query.filter_by(name=army_name.data).first()
        if not army_name.data.isalnum():
            raise ValidationError('Army name must contain only letters and numbers')
        if army:
            raise ValidationError('This army name already exists')

app/routes/attack.py
import math
import operator
from flask import render_template, abort, Blueprint
from flask_login import login_required, current_user
from app import db
from app.models.user import User
from app.models.army import BattleResult
from app.utils.shop import SHOP_ITEMS
from app.permissions.permissions import army_name_required

attack = Blueprint('attack', __name__, template_folder='templates')


@attack.route('/')
@attack.route('/<page_num>')
@login_required
@army_name_required
def index(page_num=None):
    if page_num is not None:
        page_num = int(page_num)
    users = sorted(User.query.all(), key=operator.attrgetter('army.field'), reverse=True)
    sum_users = math.ceil(len(users)/10)
    users_lists = [users[x:x+10] for x in range(0, sum_users*10, 10)]
    if page_num is None or page_num <= 0:
        for users_list in users_lists:
            if current_user in users_list:
                page_num = users_lists.index(users_list) + 1
                break
    return render_template('attack/index.html', users_lists=users_lists, page_num=page_num, num_lists=sum_users)


@attack.route('/battle_results/<int:battle_result_id>')
def battle_results(battle_result_id):
    battle_result = BattleResult.query.get_or_404(battle_result_id)
    if current_user.army not in [battle_result.attacker_army, battle_result.attacked_army]:
        abort(404)
    if current_user.army == battle_result.attacker_army:
        battle_result.viewed_by_attacker = True
    else:
        battle_result.viewed_by_attacked = True
    db.session.commit()
    return render_template('attack/battle_result.html', battle_result=battle_result, shop_items=SHOP_ITEMS)

app/routes/auth.py
from app.models.user import User
from app.utils.user import create_user
from app.forms.auth import LoginForm, RegistrationForm
from app.routes.google_auth import google_logout
from flask import Blueprint, url_for, flash, redirect, request, render_template
from flask_login import login_user, logout_user

auth = Blueprint('auth', __name__, template_folder='templates')


@auth.route('/login', methods=['POST'])
def login():
    form = LoginForm(**request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user, remember=form.remember.data)
        next_url = request.args.get('next', 'base.index')
        return redirect(url_for(next_url))
    return render_template('home/index.html',
                           login_form=form,
                           registration_form=RegistrationForm(),
                           js_vars={
                               'invalidFormButton': 'login-btn'
                           })


@auth.route('/register', methods=['POST'])
def register():
    form = RegistrationForm(**request.form)
    if form.validate_on_submit():
        user = create_user(email=form.email.data, password=form.password.data, army_name=form.army_name.data)
        login_user(user, remember=False)
        return redirect(url_for('home.index'))
    return render_template('home/index.html',
                           login_form=LoginForm(),
                           registration_form=form,
                           js_vars={
                               'invalidFormButton': 'registration-btn'
                           })


@auth.route('/logout')
def logout():
    # logout possible google user
    google_logout()
    logout_user()
    flash('You are now logged out')
    return redirect(url_for('home.index'))

app/routes/base.py
from dataclasses import dataclass
from flask import render_template, Blueprint
from flask_login import login_required, current_user
from app.permissions.permissions import army_name_required

base = Blueprint('base', __name__, template_folder='templates')


@dataclass
class UserResources:
    amount: int
    picture: str


def get_user_resources():
    user_resources = {
        "coin": UserResources(current_user.army.coin, 'coin'),
        "metal": UserResources(current_user.army.metal, 'metal'),
        "wood": UserResources(current_user.army.wood, 'wood'),
        "field": UserResources(current_user.army.field, 'field'),
        "diamond": UserResources(current_user.army.diamond, 'diamond'),
    }
    return user_resources


@base.route('/')
@login_required
@army_name_required
def index():
    user_resources = get_user_resources()
    return render_template('base/index.html', user_resources=user_resources)

app/routes/mail.py
from app.models.army import BattleResult
from app.models.user import Mail
from app.permissions.permissions import army_name_required
from flask import Blueprint, render_template
from flask_login import login_required, current_user

mail = Blueprint('mail', __name__, template_folder='templates')


@mail.route('/')
@login_required
@army_name_required
def index():
    attacker_battle_results = (BattleResult.query
                               .filter_by(attacker_army_id=current_user.army.id)
                               .order_by(BattleResult.timestamp.desc()).all())
    attacked_battle_results = (BattleResult.query
                               .filter_by(attacked_army_id=current_user.army.id)
                               .order_by(BattleResult.timestamp.desc()).all())
    user_mails_received = (Mail.query.filter_by(recipient_id=current_user.id)
                           .order_by(Mail.timestamp.desc()).all())

    return render_template('mail/index.html',
                           attacker_battle_results=attacker_battle_results,
                           attacked_battle_results=attacked_battle_results,
                           user_mails_received = user_mails_received)


@mail.app_template_filter('result_to_class_name')
def jinja_result_to_class_name(did_attacker_win, is_attacker):
    if is_attacker:
        if did_attacker_win is True:
            return 'success'
        elif did_attacker_win is False:
            return 'danger'
        else:
            return 'warning'
    else:
        if did_attacker_win is True:
            return 'danger'
        elif did_attacker_win is False:
            return 'success'
        else:
            return 'warning'

app/routes/profile.py
from app import db
from app.models.army import Army
from app.forms.profile import SetArmyNameForm
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user


profile = Blueprint('profile', __name__, template_folder='templates')


@profile.route("/<army_name>")
@login_required
def index(army_name):
    Army.query.filter_by(name=army_name).first_or_404()
    field = Army.query.filter_by(name=army_name).first().field
    clan = Army.query.filter_by(name=army_name).first().clan
    return render_template('profile/index.html', name=army_name, field=field, clan=clan)


@profile.route('/set_army_name', methods=['GET', 'POST'])
@login_required
def set_army_name():
    if current_user.army.name:
        return redirect(url_for('base.index'))
    form = SetArmyNameForm()
    if form.validate_on_submit():
        current_user.army.name = form.army_name.data
        db.session.commit()
        next_url = request.args.get('next', 'base.index')
        return redirect(url_for(next_url))
    return render_template('profile/set_army_name.html', form=form)

app/routes/shop.py
from app.utils.shop import SHOP_ITEMS, TECH_UPGRADES
from app.permissions.permissions import army_name_required
from flask import render_template, Blueprint
from flask_login import login_required

shop = Blueprint('shop', __name__, template_folder='templates')


@shop.route("/")
@login_required
@army_name_required
def index():
    return render_template('shop/index.html',
                           shop_items=SHOP_ITEMS,
                           tech_upgrades=TECH_UPGRADES)

app/templates/attack.html
{% extends "layout.html" %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/attack.css') }}">
    {% endblock styles %}

    {% block content %}
   <div class="main-table-container">
        <div class="semi-table-container">
            <table class="table">
                <thead>
                    <tr id="shop-cat">
                        <th id="weapon">Army</th>
                        <th id="cost">Field</th>
                        <th id="power">Clan</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users_lists[page_num] %}
                        <tr class="tr0">
                            {% if user == current_user %}
                                <td><a class="army-name-current" href="{{ url_for('profile.index', name=user.army.name) }}">{{ user.army.name }}</a></td>
                            {% else %}
                                <td><a class="army-name" href="{{ url_for('profile.index', name=user.army.name) }}">{{ user.army.name }}</a></td>
                            {% endif %}
                            <td>{{ user.army.field }}</td>
                            <td>{{ user.army.clan }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="next-previous-buttons">
                <div class="p-page">
                    {% if page_num >= 1 %}
                        <a href="{{ url_for('attack.index', page_num=page_num - 1) }}">Previous page</a>
                    {% endif %}
                </div>
                <div class="n-page">
                    {% if page_num + 1 < num_lists %}
                        <a href="{{ url_for('attack.index', page_num=page_num + 1) }}">Next Page</a>
                    {% endif %}
                </div>
            </div>
        </div>
   </div>
{% endblock content %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/attack.js') }}"></script>
{% endblock scripts %}

app/templates/base.html
{% extends "layout.html" %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
{% endblock styles %}

{% block content %}
    <div class="user-army-container">
    <div id="army-name">{{ current_user.army.name }}</div>
        <div class="tables">
            <div class="resources">
                {% for resource in user_resources %}
                    <div class="resource">
                        <img class="img" src="{{ url_for('static', filename='images/'+user_resources[resource].picture+'.png') }}">
                        <div id="{{ resource }}">
                            <div class="resource-name">{{ resource }}</div>
                            <div class="{{ user_resources[resource].picture }}-amount">{{ user_resources[resource].amount }}</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        <div class="user-army">
        </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
{% endblock scripts %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='images/favicon.ico') }}"/>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">
    <!-- Layout css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    {% block styles %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    {% block title %}{% endblock %}
    {{ moment.include_jquery() }}
    {{ moment.include_moment() }}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top mb-3">
        <a class="navbar-brand" href="{{ url_for('home.index') }}">Game</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="hamburger-line"></span>
            <span class="hamburger-line middle-line"></span>
            <span class="hamburger-line"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-around" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('base.index') }}">Base</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('shop.index') }}">Shop</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('attack.index', page_num=0) }}">Attack</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="#">Clan</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('mail.index') }}">Mail</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="#">Vacation</a>
                </li>
            </ul>
            {% if current_user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item mx-2">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav">
                    <li class="nav-item mx-2">
                        <a id="login-btn" class="nav-link" href="javascript: void(0);">Login</a>
                    </li>
                    <li class="nav-item mx-2">
                        <a id="registration-btn" class="nav-link" href="javascript: void(0);">Register</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
    <div class="container mb-4">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="footer text-center">
        <p class="mb-0 py-1 text-white">All Rights Reserved &copy; WebGame <span id="copyright-year"></span></p>
    </footer>
    {% block scripts %}
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js"></script>
        <script>
            {% if js_vars %}
                window.jsVars = {{ js_vars | safe  }};
            {% else %}
                window.jsVars = {};
            {% endif %}
            document.getElementById('copyright-year').textContent = new Date().getFullYear();
        </script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock scripts %}
</body>
</html>

app/templates/profile.html
{% extends "layout.html" %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
{% endblock styles %}

{% block content %}
    <div class="big-profile-container">
        <div class="profile-container">
            <div class="avatar">
                <div class="avatar-box">
                    <span>Avatar</span>
                </div>
            </div>
            <div class="army">
                <div class="army-box">
                    <div>
                        <span class="army-name">{{ name }}</span>
                    </div>
                    <div class="army-box-div">
                        <span>Field: </span>
                        {{ field }}
                    </div>
                    <div class="army-box-div">
                        <span>Clan: </span>
                        {{ clan }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
{% endblock scripts%}

app/templates/shop.html
{% extends "layout.html" %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/shop.css') }}">
{% endblock styles %}

{% block content %}
    <div class="table-container">
        <div class="table-div">
        <div
                id="user-resources"
                data-army-gold="{{ current_user.army.gold }}"
                data-army-metal="{{ current_user.army.metal }}"
        >
            <div>
                <span>gold: <span id="current-gold-amount">{{ current_user.army.gold }}</span></span>
                <img class="img" src="{{ url_for('static', filename='images/gold.png') }}">
            </div>
            <div>
                <span>metal: <span id="current-metal-amount">{{ current_user.army.metal }}</span></span>
                <img class="img" src="{{ url_for('static', filename='images/metal.png') }}">
            </div>
        </div>
            <table class="table">
                <thead>
                    <tr id="shop-cat">
                        <th id="weapon">Weapons</th>
                        <th id="cost">Cost</th>
                        <th id="power">Power</th>
                        <th>Buy</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in shop_items %}
                        <tr class="tr-item">
                            <td class="shop-item">
                                <img class="wep-img" src="{{ url_for('static', filename='images/'+shop_items[item].picture_name+'.png') }}">
                            </td>
                            <td class="td-item-cost">
                                <div>
                                    <h5 class="item-cost">{{ shop_items[item].gold }}</h5>
                                    <img class="img" src="{{ url_for('static', filename='images/gold.png') }}">
                                </div>
                                <div>
                                    <h5 class="item-cost">{{ shop_items[item].metal }}</h5>
                                    <img class="img" src="{{ url_for('static', filename='images/metal.png') }}">
                                </div>
                            </td>
                            <td class="td-item-power">
                                <span class="item-power">{{ shop_items[item].power }}</span>
                                <img class="img" src="{{ url_for('static', filename='images/power.png') }}">
                            </td>
                            <td class="td-button">
                                <div class="item-amount">
                                    you own: <span class="current-amount">{{ current_user.army.get_item_amount(item) }}</span>
                                </div>
                                <input  class="amount" placeholder="0" type="text">
                                <button
                                        class="buy-btn"
                                        data-item="{{ item }}"
                                        data-cost-gold="{{ shop_items[item].gold }}"
                                        data-cost-metal="{{ shop_items[item].metal }}"
                                >Buy</button>
                                <div class="purchase-result"></div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/shop.js') }}"></script>
{% endblock scripts %}


 